### ISSUE TITLE
1280 hack off

### ISSUE THREAD

**Issue by drserajames** [acorg/lispmds#24]
I get an error when I try to take the 1280 hack off:

CL-USER(2): (1280 hack off)
Error: Attempt to take the value of the unbound variable `HACK'.
  [condition type: UNBOUND-VARIABLE]

**Comment by davidfburke** [comment]
You forgot the dashes.
(1280-hack-off)  not (1280 hack off)

**Comment by drserajames** [comment]
Magic!  Thanks
